module.exports = {
  out: './docs/reference',
  readme: 'none',
  includes: './',
  exclude: [],
  mode: 'file',
  theme: 'markdown',
  mdEngine: 'github',
  name: 'EmberFire',
  ignoreCompilerErrors: true,
  excludeProtected: true,
  excludeExternals: true,
  excludeNotExported: true,
  excludePrivate: true,
  gitRevision: 'v3.0.0-rc.1',
};
